[project]
name = "openmensa"
version = "0"
requires-python = ">= 3.10"
dependencies = [
  "mdx-truly-sane-lists~=1.2",
  "mkdocs-awesome-pages-plugin~=2.10.1",
  "mkdocs-git-revision-date-plugin~=0.3.2",
  "mkdocs-material~=9.7.0",
]
