
development: &dev
  github:
    key: 592cd23d78131215954c
    secret: 951c3b87f8798128f4fac6b9553ea92269edc515
  twitter:
    key: m1PplbhUQdVfB1zfkY3kZg
    secret: ysozRyiD6bKjy8GBmMjPqVjyyVG5unX5rVEqE4YxtBU
  facebook:
    key: 125394024272497
    secret: 44f16f3762328df5cc42c1854226036b

test:
  github:
    key: test
    secret: test
  twitter:
    key: test
    secret: test
