# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
#
# Make sure the secret is at least 30 characters and all random, no
# regular words or you'll be exposed to dictionary attacks. You can use
# `rails secret` to generate a secure secret key.
#
secret_key_base: 14e5342fdc53557a9fd4096da23b4e8ac4613909bff25211aad8592306cebe41520a2e5acb68f1ad64b3571e6a4d1918d22b1bea153587705b8762920e3b7b6c

sentry:
  # The DSN tells the SDK where to send events. If this value isn't
  # provided, the SDK will try to read it from the SENTRY_DSN
  # environment variable. If that variable doesn't exist, the SDK won't
  # send any events.
  # dsn: https://examplePublicKey@o0.ingest.sentry.io/0
